In [1]:
'''
Practical Questions
Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.'''

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

# Print the transposed array
print("\nTransposed array:")
print(transposed_array)

Original array:
[[ 60  26 100]
 [ 93  60  94]
 [ 93  13  76]]

Transposed array:
[[ 60  93  93]
 [ 26  60  13]
 [100  94  76]]


In [2]:
'''
Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array. '''

import numpy as np

# Generate a 1D NumPy array with 10 elements
array = np.arange(10)

# Print the original array
print("Original 1D array:")
print(array)

# Reshape the array into a 2x5 array
reshaped_2x5 = array.reshape(2, 5)
print("\nReshaped to 2x5 array:")
print(reshaped_2x5)

# Reshape the array into a 5x2 array
reshaped_5x2 = array.reshape(5, 2)
print("\nReshaped to 5x2 array:")
print(reshaped_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
'''
Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array. '''

import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.random((4, 4))

# Print the original array
print("Original 4x4 array:")
print(array)

# Add a border of zeros around the array
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 array with border of zeros:")
print(bordered_array)

Original 4x4 array:
[[0.82065564 0.82228856 0.90947933 0.27801937]
 [0.06053764 0.44973694 0.66280862 0.77295092]
 [0.98849543 0.67723394 0.45396874 0.9171393 ]
 [0.82706111 0.419608   0.38314219 0.58103903]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.82065564 0.82228856 0.90947933 0.27801937 0.        ]
 [0.         0.06053764 0.44973694 0.66280862 0.77295092 0.        ]
 [0.         0.98849543 0.67723394 0.45396874 0.9171393  0.        ]
 [0.         0.82706111 0.419608   0.38314219 0.58103903 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
'''
Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.'''


import numpy as np
# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
# Print the resulting array
print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

# Print the original array and the transformed arrays
print("Original array:")
print(array)

print("\nUppercase transformation:")
print(uppercase_array)

print("\nLowercase transformation:")
print(lowercase_array)

print("\nTitle case transformation:")
print(titlecase_array)

Original array:
['python' 'numpy' 'pandas']

Uppercase transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase transformation:
['python' 'numpy' 'pandas']

Title case transformation:
['Python' 'Numpy' 'Pandas']


In [6]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Print the original array and the transformed array
print("Original array:")
print(words_array)

print("\nArray with spaces between characters:")
print(spaced_words_array)

Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [7]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
# Add a small constant to avoid division by zero if necessary
division = array1 / (array2 + 1e-10)

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [8]:
#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


In [9]:
#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1001, size=100)

# Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in array if is_prime(num)]

# Print the array and the prime numbers found
print("Array of random integers:")
print(array)

print("\nPrime numbers in the array:")
print(prime_numbers)

Array of random integers:
[991 114  48 124   1 410 422 719 461 613 484 799 645 169 693 351 275 779
 714  61 236 725 183 947 302 559 136 975 767 606 478 901 681 356 211 992
 726 167 465 964 915 414 356 161 613 248 142 318 809 925 221 887  65 759
 982 525 139 513 801  81 980 855 255 743 392  11   3 612 638 997 440   1
 813  88 433 128 342 805 755 236 453 194 377 884 184 438 577 134 770 561
 270 642 583  80 101 719 914 324 758 110]

Prime numbers in the array:
[991, 719, 461, 613, 61, 947, 211, 167, 613, 809, 887, 139, 743, 11, 3, 997, 433, 577, 101, 719]


In [10]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Here we use random temperatures between -10 and 35 degrees Celsius
daily_temperatures = np.random.randint(-10, 36, size=30)

# Reshape the array into a 2D array where each row represents a week
# Assuming 5 weeks of 6 days each
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the daily temperatures and weekly averages
print("Daily temperatures for the month:")
print(daily_temperatures)

print("\nWeekly temperatures:")
print(weekly_temperatures)

print("\nWeekly averages:")
print(weekly_averages)

Daily temperatures for the month:
[-7 19 13 -7 34 16 15 15 10  4 12 -5  3 18  1 13 25 -7 -3  0 11 34 23  1
 14 31 -6 16 31 26]

Weekly temperatures:
[[-7 19 13 -7 34 16]
 [15 15 10  4 12 -5]
 [ 3 18  1 13 25 -7]
 [-3  0 11 34 23  1]
 [14 31 -6 16 31 26]]

Weekly averages:
[11.33333333  8.5         8.83333333 11.         18.66666667]
